name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4', '8.5']
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      CACHE_STORE: array
      APP_ENV: testing
      APP_KEY: base64:u64/L+j85pQ9+J8u7k6uY9u6/n58n5o6uY9u6/n58n5o=

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2
    - uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Copy .env
      run: cp .env.example .env

    - name: Create Database File
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install Node Dependencies
      run: npm i

    - name: Generate key
      run: php artisan key:generate

    - name: Build Assets
      run: npm run build

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
