name: tests

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4', '8.5']
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      CACHE_STORE: array
      APP_ENV: testing
      APP_KEY: base64:u64/L+j85pQ9+J8u7k6uY9u6/n58n5o6uY9u6/n58n5o=

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm i

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Install Dependencies (No Scripts)
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Create Database File
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Finalize Dependencies (With Scripts)
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest
